### PR TITLE
Update encrypter not to use sun.misc classes. Also remove unused code…

### PR DESCRIPTION
**Pull request by makiam**
Also remove unused code… Add some test code

### CODE REVIEW

**Comment by Sailsman63** [comment]
This needs to be two separate commits.

Otherwise it looks good, though I may review the tests a little more thoroughly after teh commit is split.

**Comment by Sailsman63** [comment]
Removal of the internal test methods should also be done on the encrypter test branch.

There also has been no decision on what logging arrangement AOI as a whole should use. (Though I will post in ArtOfIllusion/ArtOfIllusion#50 later tonight about that.) Logging changes should be in another commit.

**Comment by makiam** [comment]
One of internal test methods depends on also deleted constructor and need also restore some removed imports. Lets say this just as remove unused code. ))

**Comment by Sailsman63** [comment]
> Lets say this just as remove unused code. ))

And that's exactly what needs to be in a separate commit. Updating to avoid the sun.misc classes is it's own thing.

**Pull request merged**
